### ISSUE TITLE
Will there be a Update for e10s Support?

### ISSUE THREAD

**Issue by Offerel** [marcstober/MoreBookmarksToolbar#4]
Since this is my only AddOn which disables multiprocess compatibility in my FF Installations, i would like to aks, if there will be a Update to support e10s?

**Comment by marcstober** [comment]
@Offerel thanks for letting me know how this is affecting you. I'd like to update but to be truthful am not able to give much time to this project now, so I can't say when I'll get to it. (If you have any ideas on the best way to update the code or even a pull request that is welcome!)
